#!/bin/bash

# Check for required arguments
if [ $# -ne 2 ]; then
    echo "usage: $./out_diff file_1 file_2" 1>&2
    exit 1
fi

# Make sure both arguments are files
if [ -d $1 ]; then
    echo "first argument is not a file" 1>&2
    exit 1
fi

if [ -d $2 ]; then
    echo "second argument is not a file" 1>&2
    exit 1
fi

file1=$1
file2=$2
tmp1=tmp1.txt
tmp2=tmp2.txt

sort $file1 > $tmp1
sort $file2 > $tmp2
diff $tmp1 $tmp2
rm $tmp1 $tmp2

exit 0
