#!/bin/bash

# Check for required arguments
if [ $# -ne 2 ]; then
	echo "usage: $./sort_diff file_1 file_2" 1>&2
	exit 1
fi

# Make sure both arguments are files
if [ -d $1 ]; then
	echo "first argument is not a file" 1>&2
	exit 1
fi

if [ -d $2 ]; then
	echo "second argument is not a file" 1>&2
	exit 1
fi

if [ -d "~/tmp" ]; then
	TEMP_DIR=~/tmp
else
	TEMP_DIR=/tmp
fi

# Create temp files
TEMP_FILE_1=$TEMP_DIR/sort_diff.$$.$RANDOM
TEMP_FILE_2=$TEMP_DIR/sort_diff.$$.$RANDOM
while [ "$TEMP_FILE_1" == "$TEMP_FILE_2" ]; do
	TEMP_FILE_1=$TEMP_DIR/sort_diff.$$.$RANDOM
	TEMP_FILE_2=$TEMP_DIR/sort_diff.$$.$RANDOM
done

# Sort input files and compute diffs
sort $1 > $TEMP_FILE_1
sort $2 > $TEMP_FILE_2
diff $TEMP_FILE_1 $TEMP_FILE_2

# Clean up
rm $TEMP_FILE_1 $TEMP_FILE_2

exit 0
